---
swagger: "2.0"
info:
  description: "This API defines operations that allow the viewing of various statistics\
    \ regarding an online e-Commerce retailer data from October of 2019. Due to the\
    \ nature of the data, singular POST/PUT operations will not be implemented, as\
    \ the main purpose of the API is to view historic data of the activity given a\
    \ certain time frame. However it may be possible to insert an entirely new dataset\
    \ regarding another time period."
  version: "1.0.0"
  title: "e-Commerce Data viewer"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "ecommerce.swagger.io"
basePath: "/"
tags:
- name: "product"
  description: "All product related operations"
- name: "events"
  description: "Everything regarding events on products (viewing, adding to cart and\
    \ purchasing)"
schemes:
- "https"
- "http"
paths:
  /product/listCategories:
    get:
      tags:
      - "product"
      summary: "Lists all product categories made available in the dataset"
      operationId: "listCategories"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Category"
        "400":
          description: "Error occurred"
      x-swagger-router-controller: "Product"
  /product/popularBrands:
    get:
      tags:
      - "product"
      summary: "Lists all brands in the dataset by popularity within all possible\
        \ event types (view, cart and purchase)"
      operationId: "mostPopularBrands"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Brand"
        "400":
          description: "Error occurred"
      x-swagger-router-controller: "Product"
  /product/salesByBrand:
    get:
      tags:
      - "product"
      summary: "Lists all sales made by each brand"
      operationId: "salesByBrand"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Brand"
        "400":
          description: "Error occurred"
      x-swagger-router-controller: "Product"
  /product/salePrice:
    get:
      tags:
      - "product"
      summary: "Gets the average sale price by brand"
      operationId: "salePrice"
      produces:
      - "application/json"
      parameters:
      - name: "brand"
        in: "query"
        description: "Brand name"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
        "400":
          description: "Invalid brand name."
        "401":
          description: "Error occurred."
      x-swagger-router-controller: "Product"
  /events/ratio:
    get:
      tags:
      - "events"
      summary: "Shows the ratio of all 3 event types: view, cart and purchase"
      operationId: "eventsRatio"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Event"
        "400":
          description: "Error occurred"
      x-swagger-router-controller: "Events"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Event:
    type: "object"
    required:
    - "eventType"
    properties:
      eventType:
        type: "string"
        enum:
        - "view"
        - "cart"
        - "purchase"
      eventTime:
        type: "string"
        format: "date-time"
      ratio:
        type: "number"
        format: "double"
      count:
        type: "number"
        format: "integer"
    example:
      eventTime: "2000-01-23T04:56:07.000+00:00"
      count: 6.02745618307040320615897144307382404804229736328125
      eventType: "view"
      ratio: 0.80082819046101150206595775671303272247314453125
  Brand:
    type: "object"
    required:
    - "brandName"
    properties:
      brandName:
        type: "string"
      popularity:
        type: "number"
        format: "double"
      sales:
        type: "number"
        format: "int64"
    example:
      brandName: "brandName"
      popularity: 0.80082819046101150206595775671303272247314453125
      sales: 6.02745618307040320615897144307382404804229736328125
  Product:
    type: "object"
    properties:
      brand:
        $ref: "#/definitions/Brand"
      price:
        type: "number"
        format: "double"
      category:
        $ref: "#/definitions/Category"
    example:
      price: 0.80082819046101150206595775671303272247314453125
      category:
        name: "name"
      brand:
        brandName: "brandName"
        popularity: 0.80082819046101150206595775671303272247314453125
        sales: 6.02745618307040320615897144307382404804229736328125
  Category:
    type: "object"
    properties:
      name:
        type: "string"
    example:
      name: "name"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
